DELIMITER = ","
HEALTH_CHECK_MSG = "session HTTP server started successfully"
DETAIL_404_DOC = "Error 404. Documents not found"
DETAIL_404_SESSION = "Error 404. Session not found"
DETAIL_500 = "Error 500. Internal server error"